### ISSUE TITLE
Bots wont answer questions

### ISSUE THREAD

**Issue by Mikerific** [idiidk/kahoot-tools#12]
When a question comes up the bots wont answer it at all...

**Comment by SimDoes** [comment]
1) Dont make them ghosts, it messes up the score for some reason.
2) Select the bots that you want to answer (at the bottom).
3) Then at the top click on the answer you want to send.

**Comment by idiidk** [comment]
Yep that's true. The ghosts aren't really supposed to act as players so it messes up a lot of code on the server side. Just use normal players. Thanks @SimDoes!
