### ISSUE TITLE
No style or script when I try to add it to my website?

### ISSUE THREAD

**Issue by vincent4v** [idiidk/kahoot-tools#15]
Kahoot.ml seems to have these scripts in index.html:
<script type="text/javascript" src="manifest.85f4f337e94b40a6c472.js"></script><script type="text/javascript" src="vendor.27411fd1709d3087158d.js"></script><script type="text/javascript" src="bundle.35e4582b556c31a22581.js"></script>

I think this is what is causing the style to not work when I install it on my own website?

**Comment by idiidk** [comment]
Did you build kahoot-tools on your server? The filed get automatically injected on build

**Comment by idiidk** [comment]
Closed due to inactivity

**Comment by vincent4v** [comment]
@idiidk Sorry about the late response.
Could i install it without npm though?

**Comment by idiidk** [comment]
You could, but you would have to host the CORS proxy on another server. You should also build the JavaScript and html on another server or pc where you do have access to npm.

**Comment by vincent4v** [comment]
@idiidk Ok thanks 😀
