### ISSUE TITLE
2 Factor Verification Not Bypassing

### ISSUE THREAD

**Issue by vincent4v** [idiidk/kahoot-tools#16]
When it has the 2 factor verification on it, it shows a message, but then it doesn't seem to work.

**Comment by idiidk** [comment]
Welp, Kahoot probably patched it then. You could try fiddling with the timings a bit, don't really know if that would work tho.

**Comment by vincent4v** [comment]
@idiidk ok thanks

**Comment by vincent4v** [comment]
@idiidk It looks like they changed the time of the 2 step join to 7 seconds instead of 6 which i think it was before

**Comment by idiidk** [comment]
Fixed in latest commit
