### ISSUE TITLE
Starting a server and joining it in the same window creates infinite success loop.

### ISSUE THREAD

**Issue by arm32x** [idiidk/kahoot-tools#18]
1. Create a Versus Example server in the servers tab, and copy the game pin.
 2. Join it with a regular Kahoot client.
 3. Join it in the game tab **in the same window** as the server.
 4. You have infinite success now.

**Comment by idiidk** [comment]
Servers aren't officially supported anymore. This is also a pretty specific bug that doesn't really hinder the use of the app, therefore: wontfix
