### ISSUE TITLE
Error Game not found!

### ISSUE THREAD

**Issue by Eilip999** [idiidk/kahoot-tools#21]
When i enter game pin on my site Error Game not found! appears. I use default ports. How to solve this?  My site: https://testdomena.hekko24.pl
I used this tutorial to deploy app https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-18-04

**Comment by Eilip999** [comment]
I figured out that i have problem with cors server. However i still don't know how to repair this. I tried changing some values in config.json and in nginx files but this didn't work. I don't know how to configure cors port on nginx. 
Anyone got any ideas?

**Comment by Eilip999** [comment]
solved

**Comment by DolphinGamerYT** [comment]
How to solve it?
