### ISSUE TITLE
Kahoot UUID from GamePIN... easy way?

### ISSUE THREAD

**Issue by Enter03** [idiidk/kahoot-tools#23]
Hello!
I am developing a tool for Android that displays correct answers for Kahoot quizzes in form of ApplicationOverlay (like Facebook Messenger overlay) over Kahoot App activities.
Is there any easy way of extracting **KahootID** from **GamePIN**?
Prescribing GUID from teachers URL isn't always _that easy_, especially if teacher turns on fullscreen mode.

From MITM analysis, I figured that I needed to call this endpoint: https://create.kahoot.it/rest/kahoots/[INSERT UUID/GUID here]
Then I can deserialize response to nice object. But obviously I cannot insert GamePIN (wchich is **int**) as **Guid**.

This is last problem that I need to solve for my project.
Thanks for help, I know that my issue isn't issue of Kahoot-Tools but I couldn't find any alive Kahoot repo or anyone who codes Kahoot "hacks". And sorry for my bad English ;)

**Comment by idiidk** [comment]
I faced that problem aswell. There is no way to get the guid 100% of the time. The only way I found was to call the search rest API and search for the name of the kahoot. From that request you can het the uuid

**Comment by EvanKHuang** [comment]
I'm looking for that too...

**Comment by Adrianq88** [comment]
> I faced that problem aswell. There is no way to get the guid 100% of the time. The only way I found was to call the search rest API and search for the name of the kahoot. From that request you can het the uuid


Hi can you please tell me more about how to get quiz name from API and then quiz uuid?
