### ISSUE TITLE
[feature request] publish NPM library

### ISSUE THREAD

**Issue by reteps** [idiidk/kahoot-tools#25]
It would be awesome if we could separate the application and logic into two different repos. If you publish a npm package / kahoot library, it would make it much easier for people to use the work you have done.

I would be willing to fork and create the NPM package or minified kahoot library if you do not want to, tell me if this an acceptable option.

I would love to use the work you have compiled in my own project.

**Comment by idiidk** [comment]
Thanks for showing so much interest in the project and my work! I would totally be willing to rewrite the kaboom lib as a separate package, as this would also give me the ability to fix some messy code. I’m not really able to give an eta yet, but expect it somewhere at the end of the week.

Thanks again for this great feature request

**Comment by reteps** [comment]
Awesome! looking forward to it.

**Comment by idiidk** [comment]
Library beta 0.1.1 finished!
https://github.com/idiidk/kahoot-api
