### ISSUE TITLE
Bots dont join.

### ISSUE THREAD

**Issue by ZiroGX2** [idiidk/kahoot-tools#3]
Bots do not join the game. Its says they have but they never do. I tried small and large numbers

**Comment by idiidk** [comment]
Does the game have 2FA enabled? And what version of kahoot-tools are you using?

**Comment by ZiroGX2** [comment]
Pretty sure its latest. And no 2fa.

**Comment by idiidk** [comment]
It should be fixed in the latest update! @ZiroGX2
