### ISSUE TITLE
Kahoot updated api

### ISSUE THREAD

**Issue by SimDoes** [idiidk/kahoot-tools#35]
http://prntscr.com/ork5qt
Kahoot updated to v2 api
Now only joining the game through the bot works, adding bots doesn't.
Time to update the requests a bit  ¯\_(ツ)_/¯

**Comment by idiidk** [comment]
Okay, so v2 still works fine, only ghosts are fucked. They probably haven't fully updated to the new api yet tho, so there are more things bound to break. I'll add the captcha and stuff to the kahoot-api library and update them in kahoot-tools.
