### ISSUE TITLE
Update request made for new user

### ISSUE THREAD

**Issue by reteps** [idiidk/kahoot-tools#36]
https://github.com/idiidk/kahoot-tools/blob/b5cdef6a3de97bb94b4448c426a05b543dfe3988/app/kahoot.js#L220

Update to fix #35. See https://github.com/reteps/kbot/blob/master/klib.py for reference.
This is the code that generated the captchaToken:
https://repl.it/repls/WholeCrimsonFlashdrives

send this json data:
```
{"host": "kahoot.it", 
"gameid": pin,
"captchaToken": "KAHOOT_TOKEN_eyJ2ZXJzaW9uIjoiIn0=",
"name": name, 
"type": "login"}
```

**Comment by idiidk** [comment]
Alright, so it's just about the auth code? Because I've tested the project yesterday and it still worked fine. Also, can't you just do ```btoa(JSON.stringify({version:""}))``` to generate the captcha code?

**Comment by reteps** [comment]
technically, I just copied the function they had in JS to make it.

**Comment by idiidk** [comment]
Fixed!
