### ISSUE TITLE
Error on test website

### ISSUE THREAD

**Issue by Taherismail17** [idiidk/kahoot-tools#4]
Hello, 

I was unable to get this on a test website. Is it possible to run this outside of localhost and on a webserver?

Thanks

**Comment by idiidk** [comment]
@Taherismail17 Yeah, of course! The only problem is the cors server which most free NodeJS hosters wont allow you to execute. The only solution is buying a vps or installing Linux and Node on another machine you have and forwarding the ports.

**Comment by Taherismail17** [comment]
Awesome! Ill have a look at implementing it with Heroku first. 
I hope its alright if I make a client app for it on iOS (will definitely credit you for the server stuff)?

I wasn't able to get the web scraping done in swift and a couple classmates wanted to see if it was possible as an app. 

Thanks for the quick reply :)

**Comment by idiidk** [comment]
No problem if you give proper credit.

Be warned though, every connection to Kahoot except for the first one is made from the client side, so it’s not possible to just create a server side api. You should look into implementing kahoot.v4.js in Swift if you want to go truly native. 

Dont know exactly what you want to do but just some friendly advice.
