### ISSUE TITLE
Error: Network Error

### ISSUE THREAD

**Issue by DolphinGamerYT** [idiidk/kahoot-tools#40]
I installed it, but hosting in port 81 instead of 80, and cors port is open, but I'm getting this error: "**Error: Network Error**"

**Comment by idiidk** [comment]
Have you changed the config? If so can you provide me with your current configuration?

**Comment by DolphinGamerYT** [comment]
I change it. (I need to use the private ip because the public one is not mapped on the VM)

`{
  "host": "10.0.0.5",
  "corsUrl": "0.0.0.0",
  "corsPort": "3000",
  "webPort": "81"
}
`

**Comment by idiidk** [comment]
You should take a look at the network traffic from chrome or whatever browser you use. There you should see your request and why it fails.

If you still need help, hit me up on discord, idiidk#1850. It's easier communicating like that :)
