### ISSUE TITLE
premium features hacks are not included

### ISSUE THREAD

**Issue by Curioo** [idiidk/kahoot-tools#44]
title says it all

**Comment by idiidk** [comment]
what do you mean by premium feature hacks lol

**Comment by Curioo** [comment]
a user can buy a paid subscription for kahoot and create different questions.

**Comment by idiidk** [comment]
Those different question types are hard to implement. I'm currently still working on quizizz for a bit, but I might include them later on omegaboot.

**Comment by idiidk** [comment]
Omegaboot will need a major updat soon anyways

**Comment by Curioo** [comment]
im loving the fact that you're working on quizziz btw. do you know how i can get updates about that?

**Comment by idiidk** [comment]
the omegaboot discord is where I post most updates, also a great place to ask questions and give with the community!
