### ISSUE TITLE
it is not working at school

### ISSUE THREAD

**Issue by eimonpakzad** [idiidk/kahoot-tools#45]
![Screenshot 2019-11-29 at 10 07 59 AM](https://user-images.githubusercontent.com/35317687/69877448-3ca10e80-1290-11ea-8079-70abb66aa99c.png)

**Comment by idiidk** [comment]
is this self hosted or omegaboot.com?

**Comment by eimonpakzad** [comment]
![Screenshot 2019-11-29 at 10 29 16 AM](https://user-images.githubusercontent.com/35317687/69878501-1f217400-1293-11ea-89df-e7259919cb5b.png)

**Comment by eimonpakzad** [comment]
omegabot.com

**Comment by SimDoes** [comment]
Can you show the network log in the chrome console?
Click on the request and show the response and screenshot all of it together.

**Comment by eimonpakzad** [comment]
what

**Comment by eimonpakzad** [comment]
![Screenshot 2019-11-29 at 10 32 29 AM](https://user-images.githubusercontent.com/35317687/69878667-935c1780-1293-11ea-987b-ca266922b5c8.png)

**Comment by eimonpakzad** [comment]
![Screenshot 2019-11-29 at 10 32 58 AM](https://user-images.githubusercontent.com/35317687/69878705-a4a52400-1293-11ea-9298-160f232a84d6.png)

**Comment by SimDoes** [comment]
https://prnt.sc/q3x60c

**Comment by eimonpakzad** [comment]
what is that

**Comment by SimDoes** [comment]
the network tab (in the same column as console, the one you were just on)

**Comment by eimonpakzad** [comment]
![Screenshot 2019-11-29 at 10 35 58 AM](https://user-images.githubusercontent.com/35317687/69878870-0f565f80-1294-11ea-9b72-d2f76109f8a4.png)

**Comment by SimDoes** [comment]
well there you have it :)

**Comment by eimonpakzad** [comment]
![Screenshot 2019-11-29 at 10 36 29 AM](https://user-images.githubusercontent.com/35317687/69878913-21380280-1294-11ea-95f4-259a91523e57.png)

**Comment by eimonpakzad** [comment]
what

**Comment by SimDoes** [comment]
you school is blocking the request to https://test.omegaboot.com/kahoot.it/reserve/session/6293693/?1575041551030

**Comment by eimonpakzad** [comment]
what can I do

**Comment by eimonpakzad** [comment]
anyway too fix it

**Comment by SimDoes** [comment]
Well I can't really unblock the domain for you.
You could try hosting the site yourself. I would recommend getting a free trial on google cloud (https://cloud.google.com/free/)
They give you a year free which should be plenty :)

**Comment by eimonpakzad** [comment]
that will work

**Comment by eimonpakzad** [comment]
what if i use repl.it

**Comment by SimDoes** [comment]
that shit doesn't work lol

**Comment by eimonpakzad** [comment]
anyother website

**Comment by SimDoes** [comment]
idk why your school blocks test.omegaboot.com but not omegaboot.com
🤔

**Comment by eimonpakzad** [comment]
I don't know

**Comment by SimDoes** [comment]
try https://scriptos.tk/
it's another website that hosts the same bot
might not be as updated tho

**Comment by eimonpakzad** [comment]
blocked

**Comment by SimDoes** [comment]
I see you have a chromebook xD
You should try installing a vpn extension if they let you.

**Comment by eimonpakzad** [comment]
what one

**Comment by eimonpakzad** [comment]
all the vpn are trach

**Comment by SimDoes** [comment]
do you have discord? it would be easier to talk to on there

**Comment by eimonpakzad** [comment]
i have i am at school discord is blocked

**Comment by eimonpakzad** [comment]
send me some vpn to try

**Comment by SimDoes** [comment]
you could install nordvpn. there are websites like void.to which I don't condone but are there nonetheless.

**Comment by eimonpakzad** [comment]
is it free

**Comment by SimDoes** [comment]
everything is free is you know where to 👀

**Comment by eimonpakzad** [comment]
send me th right link

**Comment by SimDoes** [comment]
well I don't support this kind of stuff so I can't help you out here

**Comment by eimonpakzad** [comment]
ok tell me your discord as soon as i get home i will text you

**Comment by SimDoes** [comment]
have you ever used a search bar before

**Comment by eimonpakzad** [comment]
yes

**Comment by SimDoes** [comment]
well I don't see any problem here

**Comment by SimDoes** [comment]
@idiidk close this shit please

**Comment by eimonpakzad** [comment]
HAHA
