### ISSUE TITLE
How to get Quiz UUID?

### ISSUE THREAD

**Issue by Helixable** [idiidk/kahoot-tools#46]
Hey! I'm making a bookmarklet based Kahoot cheat. It's supposed to use the UUID to make a copy of the quiz and return all the answers. I'm converting this python script: https://github.com/ethanbrimhall/Kahoot_Cheat
to Javascript.
The thing is, it's very tedious for a player to copy down the Host's UUID from the screen, and that's if the screen even shows it. Are there any methods to get the UUID without looking at the host's screen? Or are there ways to get answers to a quiz without and Node packages? 
Thanks!

**Comment by idiidk** [comment]
Hi! Unfortunately it isn't possible to grab the quiz uuid, you're not the first one to ask btw ;p. What I do is search for the quiz name, then get the uuid that way. The client only gets the name on quiz start tho, so that's also not the most reliable way... 

Good luck tho!

**Comment by Helixable** [comment]
I see. Do you have any scripts that search for the quiz that I could use?

**Comment by idiidk** [comment]
https://github.com/idiidk/kahoot-api/blob/master/src/web/api.js

**Comment by 47countdown** [comment]
in other words this script is useless unless you have the unique ID. In which most monitors will not show due to the length of the quiz URL.
