### ISSUE TITLE
I have a question, what actually does the pirate shit?

### ISSUE THREAD

**Issue by Consoli0** [idiidk/kahoot-tools#48]
I've peeked through the source code and I am wondering, what actually does the "hacking" and stuff?

**Comment by idiidk** [comment]
Sends some packets to trick the server into thinking the client has reloggeg, the relogging pc being the omegaboot client. This "takes over" the players socket connection. It is now possible to send packets as the relogged player so you can do whatever you want :)

**Comment by Consoli0** [comment]
I meant, what actual file is doing the pirate shit?

**Comment by idiidk** [comment]
It isn't in this repo. Omegaboot is a private fork of kahoot-tools, it's code isn't free to use.

**Comment by Consoli0** [comment]
Oh, I see
