### ISSUE TITLE
Kahoot Takeover python project

### ISSUE THREAD

**Issue by danielkp1234** [idiidk/kahoot-tools#50]
Hello @idiidk, I find the Kahoot takeover experimental feature very cool :)
Can you tell me more about how it works? and how i could implement it in a Python Project 
Thanks

**Comment by idiidk** [comment]
The takeover feature works be using the relogin feature of Kahoot. You get the cid of the player you want to take over and you send a relogin, boom, taken over :D

I'm not going to tell you how to exactly implement it tho, that is a company secret. Just use the chrome network inspector and I'm sure you'll figure it out!

**Comment by theusaf** [comment]
Recently, the cid was removed from the nemesis object, so this no longer works

**Comment by idiidk** [comment]
Fuck, seriously?

**Comment by theusaf** [comment]
Yup. They also added various other things, like blocking answers that come immediately after the question starts.

**Comment by Curioo** [comment]
Can confirm, takeover does not work anymore
