### ISSUE TITLE
suggestion all bots select at specified kahoot option

### ISSUE THREAD

**Issue by antiburen** [idiidk/kahoot-tools#8]
make all bots select the same option (actually they are divided equally)

**Comment by idiidk** [comment]
Why? And how is this an issue, it’s supposed to be this way.

**Comment by antiburen** [comment]
when i try it selecting an option only selects it for the principal user, the rest (all the bots) select random options?

**Comment by idiidk** [comment]
Yeah, thats how it’s implemented atm. I think it would indeed be better if the bot’s answer when you answer.
